# Project information
site_name: Quanta
site_url: https://qntx.github.io/quanta/
site_author: CtrlX
site_description: >-
  Quanta - Σ in innovation, harmony in finance.

# Repository
repo_url: https://github.com/qntx/quanta
repo_name: Qntx/Quanta

# Copyright
copyright: >
  Copyright &copy; 2024 - 2025 CtrlX –
  <a href="#__consent">Change cookie settings</a>

# Configuration
theme:
  name: material
  custom_dir: docs/overrides

  logo: assets/images/logos/logo-white.svg
  favicon: assets/images/logos/logo.svg

  font:
    text: Roboto
    code: Roboto Mono

  language: zh

  palette:
    scheme: slate
    primary: black

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - content.code.select
    - content.code.copy
    - content.code.annotate

# Additional configuration
extra:
  consent:
    title: Cookie 使用声明
    description: >- 
      我们使用 Cookie 记录您多次访问的行为和偏好，同时评估我们的文档效果以及用户是否能够找到所需信息。
      在您同意的前提下，您将帮助我们优化文档内容。
    consent:
    actions:
      - accept
      - reject
      - manage

  version:
    provider: mike
    default: latest
    alias: true

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Qntx
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/GitCtrlX

  generator: false

# Plugins
plugins:
  - search
  - blog:
      blog_toc: true
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - minify:
      minify_html: true

# Extra
# extra_css:
#     - assets/stylesheets/extra.css

# Hooks
# hooks:
#   - docs/overrides/hooks/socialmedia.py

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: "index.md"

  - Getting Started:
    - Getting Started: "get-started/index.md"
    - Installation: "get-started/installation.md"
    - Quick Start: "get-started/quick-start.md"
    - FAQ: "get-started/faq.md"

  - Tutorials:
    - Tutorials: "tutorials/index.md"
    - Configuration: "tutorials/configuration.md"
    - API: "tutorials/api.md"

  - Framework:
    - Framework: "framework/index.md"
    - Σ-X:
        - Σ-X: "framework/sigmax/index.md"
        - Usage: "framework/sigmax/usage.md"
        - API: "framework/sigmax/api.md"  
        - FAQ: "framework/sigmax/faq.md"
    - Σ-Data: 
        - Σ-Data: "framework/sigmadata/index.md"
        - Usage: "framework/sigmadata/usage.md"
        - API: "framework/sigmadata/api.md"
        - FAQ: "framework/sigmadata/faq.md"
    - Σ-TA:
        - Σ-TA: "framework/sigmata/index.md"
        - Usage: "framework/sigmata/usage.md"
        - Indicators: "framework/sigmata/supported_indicators.md"
        - Details: "framework/sigmata/indicators_details.md"
        - Performance: "framework/sigmata/performance.md"
        - API: "framework/sigmata/api.md"
        - FAQ: "framework/sigmata/faq.md"
    - Σ-Stats:
        - Σ-Stats: "framework/sigmastats/index.md"
        - Usage: "framework/sigmastats/usage.md"
        - API: "framework/sigmastats/api.md"
        - FAQ: "framework/sigmastats/faq.md"
    - Σ-Opt:
        - Σ-Opt: "framework/sigmaopt/index.md"
        - Usage: "framework/sigmaopt/usage.md"
        - API: "framework/sigmaopt/api.md" 
        - FAQ: "framework/sigmaopt/faq.md"
    - Σ-RL:
        - Σ-RL: "framework/sigmarl/index.md"
        - Usage: "framework/sigmarl/usage.md"
        - API: "framework/sigmarl/api.md"
        - FAQ: "framework/sigmarl/faq.md"
    - Σ-LLM:
        - Σ-LLM: "framework/sigmallm/index.md"
        - Usage: "framework/sigmallm/usage.md"
        - API: "framework/sigmallm/api.md"
        - FAQ: "framework/sigmallm/faq.md"
    - Σ-Chart:
        - Σ-Chart: "framework/sigmachart/index.md"
        - Usage: "framework/sigmachart/usage.md"
        - API: "framework/sigmachart/api.md" 
        - FAQ: "framework/sigmachart/faq.md"
    - Σ-Msg:
        - Σ-Msg: "framework/sigmamsg/index.md"
        - Usage: "framework/sigmamsg/usage.md"
        - API: "framework/sigmamsg/api.md"
        - FAQ: "framework/sigmamsg/faq.md"
    - Σ-Log:
        - Σ-Log: "framework/sigmalog/index.md"
        - Usage: "framework/sigmalog/usage.md"
        - API: "framework/sigmalog/api.md"
        - FAQ: "framework/sigmalog/faq.md"
    - Σ-Util:
        - Σ-Util: "framework/sigmautil/index.md"
        - Usage: "framework/sigmautil/usage.md"
        - API: "framework/sigmautil/api.md"
        - FAQ: "framework/sigmautil/faq.md"

  - Reference:
      - Reference: "reference/index.md"
      - CLI Commands: "reference/cli.md"
      - About: "reference/about.md"
      - Performance Metrics: 
          - Performance Metrics: "reference/performance/index.md"

  - Blog:
      - "blog/index.md"
